# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
python -m lerobot.record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --teleop.type=so100_leader \
    --teleop.port=/dev/tty.usbmodem58760431551 \
    --teleop.id=blue \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube"
```
"""

import logging
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat

import numpy as np
import rerun as rr

from lerobot.common.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.common.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.common.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.common.datasets.image_writer import safe_stop_image_writer
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
from lerobot.common.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.common.policies.factory import make_policy
from lerobot.common.policies.pretrained import PreTrainedPolicy
from lerobot.common.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
from lerobot.common.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    make_teleoperator_from_config,
)
from lerobot.common.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.common.utils.robot_utils import busy_wait
from lerobot.common.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.common.utils.visualization_utils import _init_rerun
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig


import io
import base64
import openai
from dotenv import load_dotenv
import os
from PIL import Image as PILImage
import asyncio 

import gradio as gr


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        if self.teleop is not None and self.policy is not None:
            raise ValueError("Choose either a policy or a teleoperator to control the robot")

        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


@parser.wrap()
def create_robot(cfg: RecordConfig) -> Robot:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        _init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    robot.connect()
    return robot


async def get_robot_config() -> str:
    """Return the current robot configuration."""
    robot_list = [f"{robot_id}: {description}" for robot_id, description in ROBOTS.items()]
    return "Robots configured:\n" + "\n".join(robot_list)

async def get_robots() -> str:
    """
    Get the current number of robots and their descriptions.
    """
    robot_info = [f"{robot_id}: {description}" for robot_id, description in ROBOTS.items()]
    return f"Total robots: {len(ROBOTS)}\n" + "\n".join(robot_info)

async def act(instruction: str) -> str:
    """
    Execute a generic instruction.
    Simulates the action and returns a confirmation message.
    """
    template = f"Pick the {{obj}} and place it at {{target}}"

    await asyncio.sleep(0.1)

    return f"Successfully executed: {instruction}"

async def get_workspace_description() -> str:
    # TODO: Replace with image from environment
    img = ROBOTS["main_robot_arm"]["robot"].get_observation()["overview"]
    workspace_img = PILImage.fromarray(img)

    buffer = io.BytesIO()
    workspace_img.save(buffer, format="PNG")
    buffer.seek(0)
    image_base64 = base64.b64encode(buffer.getvalue()).decode("utf-8")

    client = openai.OpenAI(api_key=openai_apikey)

    # robot_info = "\n".join([f"- {robot_id}: {description}" for robot_id, description in ROBOTS.items()])
    robot_info = "very important robot information"

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": f"""Analyze this workspace image and provide a structured response in the following format:

                                        Objects in the environment:
                                        - {{name1}}: Short description of state
                                        - {{name2}}: Short description of state

                                        Robots:
                                        - {{robot_id1}}: Short description of its current state
                                            • current pose?
                                            • what is closest object?
                                        - {{robot_id2}}: ...

                                        Task State:
                                        A list of steps describing what steps of the task need to be accomplished. In particular, which 
                                        objects need to be manipulated and how.

                                        Please identify the robots in the image and map them to the robot IDs provided. 
                                        Focus on objects, their positions, robot poses, and task-relevant details for 
                                        robotic manipulation. Use the following context:
                                        - Available robots in the system: {robot_info}
                                    """
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{image_base64}"
                            }
                        }
                    ]
                }
            ],
            max_tokens=500
        )

        description = response.choices[0].message.content
        return description

    except Exception as e:
        return f"Error analyzing workspace image: {str(e)}"


if __name__ == "__main__":

    load_dotenv()
    openai_apikey = os.getenv("OPENAI_API_KEY")

    ROBOTS = {
        "main_robot_arm": {
            "description": "Main robot arm for manipulation tasks",
            "robot": create_robot()
        },
    }

    with gr.Blocks(title="Robot MCP Server (Gradio)") as demo:
        gr.Markdown("# 🤖 Robot MCP Server")

        with gr.Tab("robot://config"):
            cfg_btn = gr.Button("Get Robot Config")
            cfg_out = gr.Textbox(lines=6)
            cfg_btn.click(get_robot_config, outputs=cfg_out)

        with gr.Tab("Workspace Analysis"):
            task_in = gr.Textbox(label="Task")
            desc_btn = gr.Button("Analyze demo.png")
            desc_out = gr.Textbox(lines=18)
            desc_btn.click(get_workspace_description, inputs=[task_in], outputs=desc_out)

        with gr.Tab("Robot Actions"):
            obj_in = gr.Textbox(label="Object")
            tgt_in = gr.Textbox(label="Target")

            res_out = gr.Textbox(lines=4)

            instr_in = gr.Textbox(label="Instruction")
            gr.Button("Act").click(act, [instr_in], res_out)

        with gr.Tab("Robots"):
            rb_btn = gr.Button("Show Robots")
            rb_out = gr.Textbox(lines=6, interactive=False)
            rb_btn.click(get_robots, outputs=rb_out)

    try:
        demo.launch(mcp_server=True)
    finally:
        for robot_dict in ROBOTS.values():
            robot_dict["robot"].disconnect()